# Generated by Django 6.0.4 on 2026-04-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='trailer_url',
            field=models.FileField(blank=True, null=True, upload_to='trailers/'),
        ),
    ]
